// Build queue service: capture tool ideas without letting them become
// avoidance, and generate scoped Claude Code prompts and spawn scripts.

import fs from "fs";
import path from "path";

export function safeSlug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50) || "idea";
}

export interface BuildIdea {
  idea: string;
  problemItSolves: string;
  targetUser: string | null;
  scope: string | null;
  definitionOfDone: string | null;
}

export function generateClaudeCodePrompt(input: BuildIdea): string {
  return [
    `# Claude Code build prompt: ${input.idea}`,
    "",
    "## Project context",
    "This tool is being built for Jamal, founder of Pulse AI Technologies (AI enquiry handling for dental and vet practices) and EY assurance data analytics apprentice in Birmingham. The tool must serve real execution, not become a distraction from Pulse outreach.",
    "",
    "## Problem it solves",
    input.problemItSolves,
    "",
    `## Target user`,
    input.targetUser ?? "Jamal (personal tool)",
    "",
    "## Scope limits",
    input.scope ?? "Smallest useful version only. No feature creep beyond the definition of done.",
    "",
    "## Definition of done",
    input.definitionOfDone ?? "A working minimal version that solves the stated problem, runnable locally.",
    "",
    "## Files likely affected",
    "New standalone project in its own directory. Do not modify Jamal OS or other existing projects unless explicitly stated.",
    "",
    "## Tests required",
    "Unit tests for core logic with Vitest or the language-appropriate equivalent. The build must pass before completion is claimed.",
    "",
    "## Rules",
    "- Local-first. No personal data leaves the machine without explicit consent.",
    "- No secrets in source code. Use environment variables and provide a .env.example.",
    "- No external write actions without explicit confirmation in the UI.",
    "- Do not use em dashes in code comments, UI copy, docs, or generated writing.",
    "- Do not fake completion. Label scaffolded work as scaffolded.",
    "- UK English.",
  ].join("\n");
}

export function generateSpawnScript(slug: string, promptFilename: string): string {
  return `#!/usr/bin/env bash
# Spawn a new Claude Code session for: ${slug}
# Generated by Jamal OS build queue.
# Safe by design: creates a sibling directory and starts Claude Code with
# the generated prompt. Never run automatically. Never destructive.
set -euo pipefail

PROMPT_FILE="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)/generated-prompts/${promptFilename}"
TARGET_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)/${slug}"

if [ ! -f "$PROMPT_FILE" ]; then
  echo "Prompt file not found: $PROMPT_FILE"
  exit 1
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "Claude Code CLI is not installed."
  echo "Install it with: npm install -g @anthropic-ai/claude-code"
  echo "Then re-run this script, or paste the prompt manually from:"
  echo "  $PROMPT_FILE"
  exit 1
fi

mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"
echo "Starting Claude Code in $TARGET_DIR with the generated prompt."
claude "$(cat "$PROMPT_FILE")"
`;
}

export function savePromptAndScript(slug: string, prompt: string): {
  promptPath: string;
  scriptPath: string;
} {
  const promptsDir = path.join(process.cwd(), "generated-prompts");
  const scriptsDir = path.join(process.cwd(), "scripts");
  fs.mkdirSync(promptsDir, { recursive: true });
  fs.mkdirSync(scriptsDir, { recursive: true });

  const promptFilename = `${slug}.md`;
  const promptPath = path.join(promptsDir, promptFilename);
  fs.writeFileSync(promptPath, prompt, "utf-8");

  const scriptPath = path.join(scriptsDir, `spawn-${slug}.sh`);
  fs.writeFileSync(scriptPath, generateSpawnScript(slug, promptFilename), { mode: 0o755 });

  return { promptPath, scriptPath };
}
